// angular/src/components/create-metro/create-metro.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-create-metro',
  templateUrl: './create-metro.component.html',
  styleUrls: ['./create-metro.component.scss']
})
export class CreateMetroComponent {

}

<mat-card>
  <mat-card-header>
    <mat-card-title>Create Metro</mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <div class="row">
      <div class="col">
        <mat-form-field>
          <mat-label>Name</mat-label>
          <input matInput>
        </mat-form-field>
      </div>
      <div class="col">
        <mat-form-field>
          <mat-label>Extended Name</mat-label>
          <input matInput>
        </mat-form-field>
      </div>
      <div class="col col-2">
        <mat-form-field>
          <mat-label>Short Name</mat-label>
          <input matInput [maxLength]="3">
        </mat-form-field>
      </div>
      <div class="col col-2">
        <mat-form-field>
          <mat-label>Population</mat-label>
          <input matInput>
        </mat-form-field>
      </div>
      <div class="col col-2">
        <mat-form-field>
          <mat-label>Metro Size Rank</mat-label>
          <input matInput>
        </mat-form-field>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <mat-form-field>
          <mat-label>Notes</mat-label>
          <textarea matInput></textarea>
        </mat-form-field>
      </div>
    </div>
  </mat-card-content>
</mat-card>

// vue/src/views/CreateMetro.vue
<template>
  <v-container>
    <v-card>
      <v-card-title>Create City</v-card-title>
      <v-card-text>
        <v-form>
          <v-row>
            <v-col>
              <v-text-field label="Name"></v-text-field>
            </v-col>
            <v-col>
              <v-text-field label="Extended Name"></v-text-field>
            </v-col>
            <v-col>
              <v-text-field label="Short Name"></v-text-field>
            </v-col>
            <v-col>
              <v-text-field label="Population"></v-text-field>
            </v-col>
            <v-col>
              <v-text-field label="Metro Size Rank"></v-text-field>
            </v-col>
          </v-row>
          <v-row>
            <v-col>
              <v-textarea label="Notes"></v-textarea>
            </v-col>
          </v-row>
        </v-form>
      </v-card-text>
    </v-card>
  </v-container>
</template>
